### ISSUE TITLE
every pocess forked by dmenu leaves a zombie sh

### ISSUE THREAD

**Issue by pfpulux** [avahe-kellenberger/nimdow#97] opened 2020-09-17 18:35 UTC
**Describe the bug**
a application forked via dmenu or a closed terminal, leaves a zombie sh process.

**To Reproduce**
1. open a terminal via dmenu or shortcut
2. close it via exit or Ctrl-D
3. check zombies via top or ps

**Expected behavior**
A forking sh should be closed after the end of a process.

```   
      ├─runsv───login───bash───startx───xinit─┬─Xorg───{Xorg}
      │                                       └─nimdow─┬─dwm_status.sh───sleep
      │                                                ├─redshift
      │                                                ├─7*[sh]
```
I think is is a `nim` problem by `startProcess` with need to be closed()

**Comment by avahe-kellenberger** [comment] 2020-09-17 18:46
I believe this is a duplicate of #54

**Closed** 2020-09-17 20:44 UTC
Labels: bug
