### ISSUE TITLE
Focus

### ISSUE THREAD

**Issue by unihernandez22** [avahe-kellenberger/nimdow#78] opened 2020-08-08 21:33 UTC
It should focus the windows following the mouse, but only bring to the front when click.
(And focus when click if it isn't focused yet)

And, when opening a new window, it should open it at the front, but always focus the window under the cursor.

**Comment by unihernandez22** [comment] 2020-08-08 21:34
Or add a config for select what you want.

**Comment by avahe-kellenberger** [comment] 2020-08-13 18:56
Duplicate of #30

**Closed by avahe-kellenberger** 2020-08-13 18:56 UTC
